server:
  port: 8082

spring:
  application:
    name: opentraum-user-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/opentraum_user
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.opentraum.user: DEBUG
    org.springframework.r2dbc: DEBUG
